name: Issue Auto-Labeler

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue based on content
        uses: andymckay/labeler@1.0.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-labeler.yml
